### ISSUE TITLE
Review/revise copy for marketing site

### ISSUE THREAD

**Issue by gusaus** [openlearninglabs/openproducer#10]
We'll need copy for the marketing/e-commerce site. I've created a wiki with the initial stab at this - 
https://github.com/openlearninglabs/pushtapeproducer/wiki

**Comment by cmaltais** [comment]
I've started work on the e-commerce site:
http://pushtape.getopenoutreach.com

**Comment by gusaus** [comment]
This is a great start! Will I be able to log-in and edit?

I'm still trying to figure out what to call it.. a lot of it depends on if the project is actually Pushtape. Please weigh in - https://www.drupal.org/node/2511038

**Comment by gusaus** [comment]
If you've been following the thread previously referenced, [you'll see that I'm now the proud maintainer of  this entire distribution!](https://www.drupal.org/node/2511038#comment-10103282). While this will require some additional work at this stage (refactoring/renaming the project, finding a co-maintainer, etc.), we'll also be able to have more control over marketing, fundraising, crediting sponsors/partners/supporters etc. I'm pretty sure what the project will be called (the project names here on github might be a clue) and I'll update the marketing copy accordingly.
