### ISSUE TITLE
Increase the max limit for file uploads

### ISSUE THREAD

**Issue by gusaus** [openlearninglabs/openproducer#16]
Current max limit 2 MB, which is low for audio files. We'll need to increase this (8MB?) and make sure limits are set on the fields themselves. 

Guillaume informed me that line 810 of /etc/php5/apache2/php.ini is where I'd make the change. Unfortunately I've yet to figure out how to change the permissions inso I can write to this file via the command line. 

Any tips, pointers, or assistance would be greatly appreciated!

**Comment by gboudrias** [comment]
You have root access :)

Just use sudo su

(obviously be careful as the root user)

**Comment by gusaus** [comment]
Aha - so I was using sudo su aegir! Shows how much of a sysadmin I am not!
