### ISSUE TITLE
Aegir not displaying sites and platforms

### ISSUE THREAD

**Issue by gusaus** [openlearninglabs/openproducer#17]
I'm not sure if this is an issue with the latest release or my particular setup, but none of my sites or platforms are displayed - is this something I can fix or is this a bug?
![sites gusaustin praxis coop 2015-08-20 22-55-06](https://cloud.githubusercontent.com/assets/113996/9402163/810f801e-478e-11e5-9dd5-b3e9c9f10fd5.jpg)

![platforms gusaustin praxis coop 2015-08-20 22-56-44](https://cloud.githubusercontent.com/assets/113996/9402193/bcf33774-478e-11e5-9cd0-b4e7a35870cb.jpg)

**Comment by gboudrias** [comment]
Seems like a bug with the default permissions, I gave you the administrator role since you'll presumably be the only user anyway.

**Comment by gusaus** [comment]
That seemed to do the trick - thanks!
