### ISSUE TITLE
Can't backup, clone, or migrate sites

### ISSUE THREAD

**Issue by gusaus** [openlearninglabs/openproducer#18]
I'm unable to backup, clone, or migrate and site in which I've imported a theme, module, or files from my local environment. It looks like some combo of chown and chmod may do the trick, but so far I get an 'Operation not permitted'.

Is there a best practice or specific instructions that could help remedy this?

**Comment by gboudrias** [comment]
Did you try a verify? When importing, you usually need to run verify to fix permissions before doing anything.

**Comment by gusaus** [comment]
Verify doesn't seem to fix anything, but I think this is just a problem with one particular site. Will try again to fix now that I'm using the proper 'sudo'.

**Comment by gboudrias** [comment]
How is this going? Let me know if you need some help with the permissions issue, it can be tricky.

(I'm still planning on creating a module to fix them for good but it's not done yet.)

**Comment by gusaus** [comment]
I didn't spend any time over the weekend, but it looks like my success rate in copying files, modules, themes is sporadic at best. It would be great if you could tell me what (and how) permissions/ownership needs to change on amypoisson.getopenproducer.com that would get backup/clone/migrate/db updates to work (verify does not seem to do anyting).  And generally speaking, should I use scp to copy custom themes/modules from my local computer? Are there any changes to ownership/permissions I need to make to get that to work? 

Ping me in the IRC when I'm around if it'll be easier to explain in real time. Thank you again for helping me learn this!

**Comment by gboudrias** [comment]
You can certainly use SCP but Git is usually the preferred workflow. Aegir now has a Git feature which allows you to create a site from a Git repo and pull the changes.

Generally speaking, the easiest way to fix permissions is to give the site folder (/var/platforms/name/sites/example.com) to the aegir user (chown aegir:aegir example.com -R), and run a verify in the frontend, which is made to fix permissions among other things.

Let me know if this helps.

**Comment by gboudrias** [comment]
(Oh you need to be root to chown in this context, not the aegir user.)

**Comment by gusaus** [comment]
Ok - I was able to resolve my specific issue with (chown aegir:aegir example.com -R). Still a bit hit/miss with permissions/ownership in general, but hopefully using a Git workflow as suggested above will help resolve. 

Will set up a related issue to ask that question!
